# Hacky secret project 3

trigger:
- main

pr:
- main

jobs:
- job: Build
  strategy:
    matrix:
      mac:
        imageName: 'macos-10.15'
        isMac: True
        cmakeTarget: shortcircuit3py
      win:
        imageName: 'windows-2019'
        isWindows: True
        cmakeTarget: shortcircuit-core
      lin:
        imageName: 'ubuntu-20.04'
        isWindows: True
        cmakeTarget: shortcircuit3py

  pool:
    vmImage: $(imageName)

  steps:
  - checkout: self
    fetchDepth: 1
    # submodules: recursive # can't do submodules here b'cuz depth=1 fails with Github


  - bash: |
      git submodule update --init --recursive
    displayName: Get SubModules

  - bash:
      cmake -Bbuild
      cmake --build build --config Debug --target $(cmakeTarget)
    displayName: Build SC3

